FROM node:lts-alpine as builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Use the Vite build output directory
FROM nginx:alpine

# Copy the built files from the builder stage to the Nginx HTML directory
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
